SENTENCES = [
    ['Proszę zwrócić uwagę, że',
     'I tak mam trzy razy mniej czasu, więc proszę mi pozwolić powiedzieć:',
     'Pańswo się się śmieją, ale',
     'Ja nie potrzebowałem edukacji sesksualnej, żeby wiedieć, że',
     'No niestety:',
     'Gdzie leży przyczyna problemu? Ja państwu powiem:',
     'Państwo chyba nie widzą, że',
     'Oświadczam kategorycznie:',
     'Powtarzam:'],
    ['właściciele niewolników',
     'związkowcy',
     'trockiści',
     'tak zwane dzieci kwiaty',
     'rozmaici urzędnicy',
     'federaści',
     'etatyści',
     'ci durnie i złodzieje',
     'ludzie wybrani głosem meneli spod budki z piwem'],
    ['po przeczytaniu "Manifestu komunistycznego"',
     'którymi się brzydzę',
     'których nienawidzę',
     'z okolic "Gazety Wyborczej"',
     'czyli taka żydokomuna',
     'odkąd zniesiono karę śmierci',
     'którymi pogardzam',
     'których miejsce w normalnym kraju jest w więzeniu',
     'na polecenie Brukseli'],
    ['udają homoseksualistów',
     'niszczą rodzinę',
     'idą do polityki',
     'zakazują góralom robienia oscypków',
     'organizują paraolimmpiady',
     'wprowadzają ustrój, w którym raz na cztery lata można wybrać sobie pana',
     'ustawiają fotoradary',
     'wydzielają buspasy'],
    ['żeby poddawać wszystkich tresurze',
     'bo taka jest ich natura',
     'bo chcą wszystko kontrolować',
     'bo nie rozumieją, że socjalizm nie działa',
     'żeby wreszcie zapanował socjalizm',
     'dokładnie tak jak tow. Janosik',
     'zamiast pozwolić ludziom zarabiać',
     'żeby wyrwać kobiety z domu',
     'bo to jest w interesie tak zwanych ludzi pracy'],
    ['co ma zresztą tyle samo sensu, co zawodu w szachac dla debili.',
     'co zostało zaplanowane w Magdalence przez śp. generała Kiszczaka.',
     'i trzeba być idiotą, żeby ten system popierać.',
     'ale nawet ja jeszcze dożyję normalnych czasów.',
     'co dowodzi, że wyskrobano nie tych, co trzeba.'
     'a zwykłym ludziom wmawiają, że im coś "dadzą".',
     '- cóż: chcieliście (tfu!) demokracji, to macie.',
     'dlatego trzeba zlikwidować koryto, a nie zmieniać świnie.',
     'a wystarczyłoby przestać wypłacać zasiłki.']
]
